/*Creación de base de datos*/
CREATE DATABASE QUINIELA;

CREATE TABLE USERS (
	USER_ID SERIAL PRIMARY KEY,
	USERNAME VARCHAR(50) UNIQUE NOT NULL,
	PASSWORD VARCHAR(50) NOT NULL,
	EMAIL VARCHAR(250) UNIQUE NOT NULL,
	/*A
	** ROL:
	** 0 -> ADMIN
	** 1 -> CLIENT
	*/
	ROL SMALLINT NOT NULL,
	LEAGUE_MASTER BOOLEAN NOT NULL,
	
	CARDNAME VARCHAR(50) NOT NULL,
	CARDNUMBER BIGINT UNIQUE NOT NULL,
	EXPIRYDATE VARCHAR(5) NOT NULL,
	SECURITYCODE SMALLINT NOT NULL,
	POSTALCODE SMALLINT NOT NULL,
	
	PAYMENT NUMERIC(15,6)
);

CREATE TABLE COUNTRIES (
	COUNTRY_ID SERIAL PRIMARY KEY,
	COUNTRY VARCHAR(50) UNIQUE NOT NULL,
	GROUPID CHAR NOT NULL,
	FLAG VARCHAR(250) UNIQUE NOT NULL
);

CREATE TABLE MATCHES (
	MATCH_ID SERIAL PRIMARY KEY,
	OPPONENT1 INT NOT NULL,
	OPPONENT2 INT NOT NULL,
	MATCHDATE DATE,
	MATCHTIME TIME,
	STADIUM VARCHAR(50) NOT NULL,
	OPPONENT1GOLS SMALLINT NOT NULL,
	OPPONENT2GOLS SMALLINT NOT NULL,
	/*
	** STATE:
	** 0 -> WAITING
	** 1 -> IN PROGRESS
	** 2 -> FINISHED
	*/
	STATE SMALLINT NOT NULL,
	/*
	** STAGE:
	** 0 -> GROUP
	** 1 -> ROUND OF 16
	** 2 -> QUATER FINALS
	** 3 -> SEMI FINALS
	** 4 -> 3RD PLACE & FINAL
	*/
	STAGE SMALLINT NOT NULL,
	
	FOREIGN KEY (OPPONENT1)
		REFERENCES COUNTRIES (COUNTRY_ID),
	FOREIGN KEY (OPPONENT2)
		REFERENCES COUNTRIES (COUNTRY_ID)
);

CREATE TABLE TEAMS (
	TEAM_ID SERIAL PRIMARY KEY,
	TEAMNAME VARCHAR(50) UNIQUE NOT NULL,
	FOR_BETTING BOOLEAN NOT NULL,
	PRICE NUMERIC(15,6) 
);

CREATE TABLE BETS(
	MATCH_ID INT NOT NULL,
	USER_ID INT NOT NULL,
	TEAM_ID INT NOT NULL,
	OPPONENT1GOLS SMALLINT NOT NULL,
	OPPONENT2GOLS SMALLINT NOT NULL,
	LASTBET TIMESTAMP NOT NULL,
	POINTS SMALLINT NOT NULL,
	
	PRIMARY KEY (MATCH_ID, USER_ID, TEAM_ID),
	FOREIGN KEY (MATCH_ID)
		REFERENCES MATCHES (MATCH_ID),
	FOREIGN KEY (USER_ID)
		REFERENCES USERS (USER_ID),
	FOREIGN KEY (TEAM_ID)
		REFERENCES TEAMS (TEAM_ID)
);

CREATE TABLE USERS_MEMBERSHIP_PAYMENT(
	USER_ID INT NOT NULL,
	TEAM_ID INT NOT NULL,
	PAYMENTDATE TIMESTAMP DEFAULT CURRENT_DATE,
	
	PRIMARY KEY (USER_ID, TEAM_ID),
	FOREIGN KEY (USER_ID )
		REFERENCES USERS (USER_ID),
	FOREIGN KEY (TEAM_ID)
		REFERENCES TEAMS (TEAM_ID)
);

CREATE TABLE USERS_PAYMENTS(
	PAYMENT_ID SERIAL NOT NULL,
	USER_ID INT NOT NULL,
	/*
	** TYPE:
	** 0 -> LEAGUE VICTORY
	** 1 -> GLOBAL VICTORY
	*/
	TYPE SMALLINT NOT NULL,
	PAYMENTDATE TIMESTAMP DEFAULT CURRENT_DATE,
	
	FOREIGN KEY (USER_ID)
		REFERENCES USERS (USER_ID)
);

DROP TABLE USERS_PAYMENTS;
DROP TABLE USERS_MEMBERSHIP_PAYMENT;
DROP TABLE BETS;
DROP TABLE TEAMS;
DROP TABLE MATCHES;
DROP TABLE COUNTRIES;
DROP TABLE USERS;


INSERT INTO USERS 
(USERNAME, PASSWORD, EMAIL, ROL, LEAGUE_MASTER, CARDNAME, CARDNUMBER, EXPIRYDATE, SECURITYCODE, POSTALCODE, PAYMENT ) 
VALUES 
('admin', '@dm!n', 'admin@gmail.com', 0, false, 'admin admin', '1000100010001000', '10/22', 101, 001, 0.00);


INSERT INTO COUNTRIES (COUNTRY, GROUPID, FLAG) VALUES ('Qatar', 'A', 'https://countryflagsapi.com/png/qatar');
INSERT INTO COUNTRIES (COUNTRY, GROUPID, FLAG) VALUES ('Ecuador', 'A', 'https://countryflagsapi.com/png/ecuador');
INSERT INTO COUNTRIES (COUNTRY, GROUPID, FLAG) VALUES ('Senegal', 'A', 'https://countryflagsapi.com/png/senegal');
INSERT INTO COUNTRIES (COUNTRY, GROUPID, FLAG) VALUES ('Paises Bajos', 'A', 'https://countryflagsapi.com/png/netherlands');
INSERT INTO COUNTRIES (COUNTRY, GROUPID, FLAG) VALUES ('Inglaterra', 'B', 'https://countryflagsapi.com/png/england');
INSERT INTO COUNTRIES (COUNTRY, GROUPID, FLAG) VALUES ('Irán', 'B', 'https://countryflagsapi.com/png/iran');
INSERT INTO COUNTRIES (COUNTRY, GROUPID, FLAG) VALUES ('Estados Unidos', 'B', 'https://countryflagsapi.com/png/the united states of america');
INSERT INTO COUNTRIES (COUNTRY, GROUPID, FLAG) VALUES ('Gales', 'B', 'https://countryflagsapi.com/png/wales');
INSERT INTO COUNTRIES (COUNTRY, GROUPID, FLAG) VALUES ('Argentina', 'C', 'https://countryflagsapi.com/png/argentina');
INSERT INTO COUNTRIES (COUNTRY, GROUPID, FLAG) VALUES ('Arabia Saudita', 'C', 'https://countryflagsapi.com/png/saudi arabia');
INSERT INTO COUNTRIES (COUNTRY, GROUPID, FLAG) VALUES ('México', 'C', 'https://countryflagsapi.com/png/mexico');
INSERT INTO COUNTRIES (COUNTRY, GROUPID, FLAG) VALUES ('Polonia', 'C', 'https://countryflagsapi.com/png/poland');
INSERT INTO COUNTRIES (COUNTRY, GROUPID, FLAG) VALUES ('Francia', 'D', 'https://countryflagsapi.com/png/france');
INSERT INTO COUNTRIES (COUNTRY, GROUPID, FLAG) VALUES ('Australia', 'D', 'https://countryflagsapi.com/png/australia');
INSERT INTO COUNTRIES (COUNTRY, GROUPID, FLAG) VALUES ('Dinamarca', 'D', 'https://countryflagsapi.com/png/denmark');
INSERT INTO COUNTRIES (COUNTRY, GROUPID, FLAG) VALUES ('Túnez', 'D', 'https://countryflagsapi.com/png/tunisia');
INSERT INTO COUNTRIES (COUNTRY, GROUPID, FLAG) VALUES ('España', 'E', 'https://countryflagsapi.com/png/spain');
INSERT INTO COUNTRIES (COUNTRY, GROUPID, FLAG) VALUES ('Costa Rica', 'E', 'https://countryflagsapi.com/png/costa rica');
INSERT INTO COUNTRIES (COUNTRY, GROUPID, FLAG) VALUES ('Alemania', 'E', 'https://countryflagsapi.com/png/germany');
INSERT INTO COUNTRIES (COUNTRY, GROUPID, FLAG) VALUES ('Japón', 'E', 'https://countryflagsapi.com/png/japan');
INSERT INTO COUNTRIES (COUNTRY, GROUPID, FLAG) VALUES ('Bélgica', 'F', 'https://countryflagsapi.com/png/belgium');
INSERT INTO COUNTRIES (COUNTRY, GROUPID, FLAG) VALUES ('Canadá', 'F', 'https://countryflagsapi.com/png/canada');
INSERT INTO COUNTRIES (COUNTRY, GROUPID, FLAG) VALUES ('Marruecos', 'F', 'https://countryflagsapi.com/png/morocco');
INSERT INTO COUNTRIES (COUNTRY, GROUPID, FLAG) VALUES ('Croacia', 'F', 'https://countryflagsapi.com/png/croatia');
INSERT INTO COUNTRIES (COUNTRY, GROUPID, FLAG) VALUES ('Brasil', 'G', 'https://countryflagsapi.com/png/brazil');
INSERT INTO COUNTRIES (COUNTRY, GROUPID, FLAG) VALUES ('Serbia', 'G', 'https://countryflagsapi.com/png/serbia');
INSERT INTO COUNTRIES (COUNTRY, GROUPID, FLAG) VALUES ('Suiza', 'G', 'https://countryflagsapi.com/png/switzerland');
INSERT INTO COUNTRIES (COUNTRY, GROUPID, FLAG) VALUES ('Camerún', 'G', 'https://countryflagsapi.com/png/cameroon');
INSERT INTO COUNTRIES (COUNTRY, GROUPID, FLAG) VALUES ('Portugal', 'H', 'https://countryflagsapi.com/png/portugal');
INSERT INTO COUNTRIES (COUNTRY, GROUPID, FLAG) VALUES ('Ghana', 'H', 'https://countryflagsapi.com/png/ghana');
INSERT INTO COUNTRIES (COUNTRY, GROUPID, FLAG) VALUES ('Uruguay', 'H', 'https://countryflagsapi.com/png/uruguay');
INSERT INTO COUNTRIES (COUNTRY, GROUPID, FLAG) VALUES ('Corea del Sur', 'H', 'https://countryflagsapi.com/png/the republic of korea');


/*
** STATE:
** 0 -> WAITING
** 1 -> IN PROGRESS
** 2 -> FINISHED
*/

/*
** STAGE:
** 0 -> GROUP
** 1 -> ROUND OF 16
** 2 -> QUATER FINALS
** 4 -> 3RD PLACE & FINAL
*/

INSERT INTO MATCHES 
(OPPONENT1, OPPONENT2, MATCHDATE, MATCHTIME, STADIUM, OPPONENT1GOLS, OPPONENT2GOLS, STATE, STAGE)
VALUES
(1, 2, '2022-11-20', '19:00', 'Al Bayt', 0, 0, 0, 0);
INSERT INTO MATCHES 
(OPPONENT1, OPPONENT2, MATCHDATE, MATCHTIME, STADIUM, OPPONENT1GOLS, OPPONENT2GOLS, STATE, STAGE)
VALUES
(5, 6, '2022-11-21', '16:00', 'Khalifa International', 0, 0, 0, 0);
INSERT INTO MATCHES 
(OPPONENT1, OPPONENT2, MATCHDATE, MATCHTIME, STADIUM, OPPONENT1GOLS, OPPONENT2GOLS, STATE, STAGE)
VALUES
(3, 4, '2022-11-21', '19:00', 'Al Thumama', 0, 0, 0, 0);
INSERT INTO MATCHES 
(OPPONENT1, OPPONENT2, MATCHDATE, MATCHTIME, STADIUM, OPPONENT1GOLS, OPPONENT2GOLS, STATE, STAGE)
VALUES
(7, 8, '2022-11-21', '22:00', 'Ahmad Bin Ali', 0, 0, 0, 0);